apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: sample-inline
spec:
  providerConfigRef:
    name: aws-eu-west-1
  forProvider:
    source: Inline
    module: |
      resource "aws_vpc" "main" {
        cidr_block       = "10.0.0.0/16"
        tags = {
          Name = var.vpcName
        }
      }
      resource "aws_subnet" "main" {
        vpc_id     = aws_vpc.main.id
        cidr_block = "10.0.1.0/24"
      }
      output "vpc_id" {
        value       = aws_vpc.main.id
      }
      output "subnet_data" {
        value = {
          "id" = aws_subnet.main.id
          "arn" = aws_subnet.main.arn
        }
      }
      variable "vpcName" {
        description = "VPC name"
        type        = string
      }
    vars:
      - key: vpcName
        value: sample-tf-inline
