---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-eu-west-1
spec:
  credentials:
  - filename: aws-creds.ini
    source: Secret
    secretRef:
      namespace: upbound-system
      name: aws-creds
      key: credentials
  configuration: |
      terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-aws-eu-west-1"
          namespace         = "upbound-system"
          in_cluster_config = true
        }
      }
      provider "aws" {
        shared_credentials_file = "aws-creds.ini"
        region = "eu-west-1"
      }
