apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: example-remote
  annotations:
    # The terraform workspace will be named 'myworkspace'. If you omit this
    # annotation it would be derived from metadata.name - e.g. 'example-remote'.
    crossplane.io/external-name: myworkspace
spec:
  forProvider:
    # Any module supported by terraform init -from-module, for example a git
    # repository. You can also specify a simple main.tf inline; see
    # workspace-inline.yaml.
    source: Remote
    module: https://github.com/crossplane/tf
    # Variables can be specified inline.
    vars:
    - key: region
      value: us-west-1
    # Variable files can be loaded from a ConfigMap or a Secret.
    varFiles:
    - source: ConfigMapKey
      configMapKeyRef:
        namespace: default
        name: terraform
        key: example.tfvars
    - source: SecretKey
      secretKeyRef:
        namespace: default
        name: terraform
        key: example.tfvar.json
      # Variables are expected to be in HCL '.tfvars' format by default. Use
      # the JSON format if your variables are in the JSON '.tfvars.json' format.
      format: JSON
  # All Terraform outputs are written to the connection secret.
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-workspace-example-inline