apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: tf-xsubnets.aws.demo.upbound.io
  labels:
    provider: aws
    implementation: terraform
spec:
  compositeTypeRef:
    apiVersion: aws.demo.upbound.io/v1alpha1
    kind: XSubnet
  resources:
    - name: tf-vpc-and-subnet
      base:
        apiVersion: tf.upbound.io/v1beta1
        kind: Workspace
        spec:
          forProvider:
            source: Inline
            module: |
              resource "aws_vpc" "main" {
                cidr_block       = "10.0.0.0/16"
                tags = {
                  Name = var.vpcName
                }
              }
              resource "aws_subnet" "main" {
                vpc_id     = aws_vpc.main.id
                cidr_block = "10.0.1.0/24"
              }
              output "vpc_id" {
                value       = aws_vpc.main.id
              }
              output "subnet_id" {
                value       = aws_subnet.main.id
              }
              variable "vpcName" {
                description = "VPC name"
                type        = string
              }
            vars:
              - key: vpcName
      patches:
        - fromFieldPath: spec.vpcName
          toFieldPath: spec.forProvider.vars[0].value
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.outputs.vpc_id
          toFieldPath: status.share.vpcId
          policy:
            fromFieldPath: Optional
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.outputs.subnet_id
          toFieldPath: status.share.subnetId
          policy:
            fromFieldPath: Optional
